<a href="https://colab.research.google.com/github/nbarc888/test-run-for-507/blob/main/epidem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
from sqlalchemy import create_engine
import seaborn
import matplotlib.pyplot as plt
import sqlite3

In [34]:
!pip freeze > packages.text

above commant creates the list into a text file under specific name

In [44]:
## data source
# https://catalog.data.gov/dataset/county-expenditures-by-category-fiscal-year-2010

data = pd.read_csv('maryland.csv')
data

,County,General Government,Public Safety,Public Works,Health/Social Services,Education/Libraries,Parks & Recreation,Debt Service,Other
0,Allegany,3.1,6.8,12.2,6.2,66.5,0.2,2.6,2.3
1,Anne Arundel,5.4,12.2,11.6,3.5,59.8,1.8,4.7,1.1
2,Baltimore City,5.7,14.3,16.7,4.8,40.6,1.5,2.9,13.5
3,Baltimore County,4.8,11.8,11.7,2.5,57.1,1.6,3.0,7.4
4,Calvert,4.0,7.3,8.1,3.1,61.4,4.1,5.5,6.5
5,Caroline,3.0,7.7,2.8,4.3,68.1,1.3,6.6,6.2
6,Carroll,6.2,5.4,6.5,3.3,64.8,0.7,6.6,6.6
7,Cecil,3.9,9.0,7.0,4.0,68.6,0.5,4.8,2.2
8,Charles,6.4,13.1,7.7,3.1,60.4,1.8,5.4,2.2
9,Dorchester,10.4,8.7,7.0,4.6,59.8,0.9,2.4,6.2
10,Frederick,4.4,10.2,8.5,4.6,63.2,1.0,4.7,3.4
11,Garrett,4.4,6.3,19.0,5.0,55.1,0.2,1.5,8.5
12,Harford,9.6,9.6,9.1,2.7,57.9,1.9,6.4,2.7
13,Howard,6.9,10.5,8.7,2.4,60.4,2.5,6.2,2.4
14,Kent,6.8,11.8,9.0,9.5,50.1,6.7,3.8,2.4
15,Montgomery,6.1,10.6,13.1,4.8,50.2,3.3,5.0,6.9
16,Prince George’s,5.4,9.6,10.6,2.2,52.7,5.6,4.1,9.8
17,Queen Anne’s,5.2,10.9,9.2,5.1,51.8,2.9,4.3,10.7
18,St. Mary’s,5.7,9.0,7.1,3.5,63.4,2.3,3.3,5.6
19,Somerset,8.3,7.3,10.2,6.2,60.2,1.8,4.4,1.6
20,Talbot,6.7,9.3,7.9,6.1,60.4,3.9,0.7,5.0
21,Washington,3.3,8.4,9.9,3.1,69.3,0.9,3.1,2.0
22,Wicomico,2.5,7.2,4.8,7.0,69.4,2.5,3.5,3.1
23,Worcester,6.7,12.4,8.9,6.6,51.6,0.8,4.6,8.4
24,Statewide,5.7,10.8,11.5,3.7,54.5,2.6,4.3,6.9

In [20]:
## create blank sqlite db with name

sqlite3.connect('mayland2010.db')

In [23]:
conn = create_engine('sqlite:///mayland2010.db')
conn

Engine(sqlite:///mayland2010.db)

In [24]:
data.to_sql('fiscal2010', conn, if_exists='replace', index=False)

25

In [29]:
sql_query1 = "select * from fiscal2010 where county like 'Harford';"
response = pd.read_sql_query(sql_query1, conn)
response

,County,General Government,Public Safety,Public Works,Health/Social Services,Education/Libraries,Parks & Recreation,Debt Service,Other
0,Harford,9.6,9.6,9.1,2.7,57.9,1.9,6.4,2.7

In [45]:
sns.barplot(x='county', y='health_social_services', data=response)
plt.xticks(rotation=90)
plt.show()

NameError: name 'sns' is not defined